[project]
name = "myrdal4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat>=0.5.6",
    "autogen-ext[openai]>=0.5.6",
    "flet[all]>=0.28.2",
    "numpy>=2.2.5",
]
